modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="naidru_packostuff"
version="Alpha 1.0.0"
displayName="Naidru's Pack of Stuff"
credits="Special Thanks to all the people that helped with ideas!"
displayURL="https://mcreator.net"
authors="Naidru"
description='''
A Pack of Random Items designed by people, created by Naidru.
'''

[[dependencies.naidru_packostuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



