modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="naidru_packostuff"
version="1.0.0"
displayName="Naidru's Pack of Stuff"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="User, MCreator"

[[dependencies.naidru_packostuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



